"""Unit tests for compatibility checking against environments and requirements."""

from prooflab.packaging.compatibility import (
    CompatibilityChecker,
    EnvironmentContext,
)
from prooflab.packaging.manifest import CompatibilityDeclaration, PackageManifest


def test_compatibility_checker_fully_compatible() -> None:
    compat = CompatibilityDeclaration(
        symbol="EURUSD",
        timeframe="H1",
        feature_names=["ret_1", "vol_10"],
        min_app_version="0.1.0",
        target_pips=20.0,
        stop_pips=15.0,
        horizon_bars=5,
    )
    manifest = PackageManifest(
        strategy_id="strat-compat",
        symbol="EURUSD",
        timeframe="H1",
        compatibility=compat,
    )

    env = EnvironmentContext(
        app_version="0.1.0",
        supported_symbols=["EURUSD", "GBPUSD"],
        supported_timeframes=["H1", "H4"],
        available_features=["ret_1", "vol_10", "rsi_14"],
    )

    checker = CompatibilityChecker(default_context=env)
    report = checker.check_compatibility(manifest)

    assert report.is_compatible is True
    assert len(report.issues) == 0
    assert "COMPATIBLE" in report.summary()


def test_compatibility_checker_default_context_and_warnings() -> None:
    # Use a standard feature generated by FeaturePipeline
    checker = CompatibilityChecker()
    available = checker.context.available_features
    sample_feature = available[0] if available else "return_1"

    compat = CompatibilityDeclaration(
        symbol="EXOTIC",
        timeframe="M7",
        feature_names=[sample_feature],
        min_app_version="0.1.0",
        target_pips=20.0,
        stop_pips=15.0,
        horizon_bars=5,
    )
    manifest = PackageManifest(
        strategy_id="strat-warnings",
        symbol="EXOTIC",
        timeframe="M7",
        compatibility=compat,
    )

    # Use default context
    checker = CompatibilityChecker()
    report = checker.check_compatibility(manifest)

    assert report.is_compatible is True
    assert len(report.warnings) == 2  # symbol warning and timeframe warning
    assert "warnings" in report.summary()


def test_compatibility_checker_incompatibilities() -> None:
    compat = CompatibilityDeclaration(
        symbol="EURUSD",
        timeframe="H1",
        feature_names=["ret_1", "super_secret_feature"],
        min_app_version="2.0.0",  # higher than app 0.1.0
        target_pips=20.0,
        stop_pips=15.0,
        horizon_bars=5,
    )
    manifest = PackageManifest(
        strategy_id="strat-incompat",
        symbol="EURUSD",
        timeframe="H1",
        compatibility=compat,
    )

    env = EnvironmentContext(
        app_version="0.1.0",
        supported_symbols=["EURUSD"],
        supported_timeframes=["H1"],
        available_features=["ret_1"],  # missing super_secret_feature
    )

    checker = CompatibilityChecker(default_context=env)
    report = checker.check_compatibility(
        manifest,
        target_symbol="GBPUSD",  # mismatch
        target_timeframe="H4",   # mismatch
    )

    assert report.is_compatible is False
    assert len(report.issues) >= 4  # version, symbol, timeframe, missing feature
    assert "INCOMPATIBLE" in report.summary()
